"""AUTO-GENERATED by scripts/generate_rna_enthalpy_tables.py — do not edit.

RNA loop ΔH (kcal/mol) for temperature-resolved RNA folding.
Source: ViennaRNA rna_turner2004.par (Mathews 1999 / Turner 2004).
Indexed to match strider.thermo.parameters_rna loop-size arrays;
ΔG sections were validated against those arrays before grafting ΔH.
Unlike DNA, RNA loop-initiation ΔH is non-zero.
"""

HAIRPIN_SIZE_DH = [
    0, 0, 1.3, 4.8, 3.6, -2.9, 1.3, -2.9, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
]

BULGE_SIZE_DH = [
    10.6, 7.1, 7.1, 7.1, 7.1, 7.1, 7.1, 7.1, 7.1, 7.1,
    7.1, 7.1, 7.1, 7.1, 7.1, 7.1, 7.1, 7.1, 7.1, 7.1,
    7.1, 7.1, 7.1, 7.1, 7.1, 7.1, 7.1, 7.1, 7.1, 7.1,
]

INTERIOR_SIZE_DH = [
    0, 0, 0, -7.2, -6.8, -1.3, -1.3, -1.3, -1.3, -1.3,
    -1.3, -1.3, -1.3, -1.3, -1.3, -1.3, -1.3, -1.3, -1.3, -1.3,
    -1.3, -1.3, -1.3, -1.3, -1.3, -1.3, -1.3, -1.3, -1.3, -1.3,
]

HAIRPIN_TRILOOP_DH = {
    'CAACG': 23.7,
    'GUUAC': 10.8,
}

HAIRPIN_TETRALOOP_DH = {
    'CAACGG': 6.9,
    'CCAAGG': -10.3,
    'CCACGG': -3.3,
    'CCCAGG': -8.9,
    'CCGAGG': -6.6,
    'CCGCGG': -7.5,
    'CCUAGG': -3.5,
    'CCUCGG': -13.9,
    'CUAAGG': -7.6,
    'CUACGG': -10.7,
    'CUCCGG': -12.9,
}

