#!/usr/bin/env python3
"""Generate ``native/src/tables_dna.rs`` from the Python source of truth.

``strider.thermo.parameters_dna`` holds the DNA nearest-neighbor energy tables
(ΔG at 37 °C, kcal/mol) used by the folding DP.  Hand-copying them into Rust
(INTERIOR_2_2 alone: 9216 entries) would silently drift; instead this script
packs each string key into a 2-bit-per-base code and emits a sorted array per
table so the Rust side can binary-search at lookup time.

The generated file is committed to the repository (like the package's own
``strider/thermo/_dna_enthalpy_generated.py``); a pytest staleness check
(``test_tables_dna_regenerated_matches_committed`` in
``tests/test_native_dp_parity.py``) regenerates and compares byte-for-byte.
Regenerate with::

    python native/codegen_tables.py

Values are emitted via Python ``repr`` floats, which round-trip exactly, so
the Rust constants are bit-identical to the Python dictionary values.
"""

from __future__ import annotations

import sys

from strider.thermo import parameters_dna as P

BASE = {"A": 0, "C": 1, "G": 2, "T": 3, "U": 3}

# (rust_const_name, python_attr, kind)  — kind: "dict" | "vec"
TABLES = [
    ("STACK", "STACK", "dict"),
    ("TERMINAL_PENALTY", "TERMINAL_PENALTY", "dict"),
    ("INTERIOR_MISMATCH", "INTERIOR_MISMATCH", "dict"),
    ("INTERIOR_1_1", "INTERIOR_1_1", "dict"),
    ("INTERIOR_1_2", "INTERIOR_1_2", "dict"),
    ("INTERIOR_2_2", "INTERIOR_2_2", "dict"),
    ("DANGLE_3", "DANGLE_3", "dict"),
    ("DANGLE_5", "DANGLE_5", "dict"),
    ("BULGE_SIZE", "BULGE_SIZE", "vec"),
    ("INTERIOR_SIZE", "INTERIOR_SIZE", "vec"),
    ("HAIRPIN_SIZE", "HAIRPIN_SIZE", "vec"),
    ("HAIRPIN_MISMATCH", "HAIRPIN_MISMATCH", "dict"),
    ("HAIRPIN_TRILOOP", "HAIRPIN_TRILOOP", "dict"),
    ("HAIRPIN_TETRALOOP", "HAIRPIN_TETRALOOP", "dict"),
    ("ASYMMETRY_NINIO", "ASYMMETRY_NINIO", "vec"),
    ("LOG_LOOP_PENALTY", "LOG_LOOP_PENALTY", "scalar"),
]

HEADER = """\
// GENERATED by native/codegen_tables.py from strider.thermo.parameters_dna —
// DO NOT EDIT BY HAND.  Run `python native/codegen_tables.py` to regenerate.
//
// Each `dict` table is a sorted `&[(u32, f64)]` keyed by the 2-bit-per-base
// packed code of its string key (see `crate::tables::pack`), enabling
// binary-search lookups without any runtime table construction.
"""


def pack(key: str) -> int:
    """2-bit-per-base packing, LSB first (mirrors crates::tables::pack)."""
    code = 0
    for i, b in enumerate(key.upper()):
        code |= BASE[b] << (2 * i)
    return code


def gen_dict(name: str, table) -> str:
    items = sorted(((pack(k), v) for k, v in table.items()), key=lambda kv: kv[0])
    lines = [f"pub static {name}: &[(u32, f64)] = &["]
    for code, val in items:
        lines.append(f"    ({code}u32, {val!r}),")
    lines.append("];\n")
    return "\n".join(lines)


def gen_vec(name: str, values) -> str:
    lines = [f"pub static {name}: &[f64] = &["]
    for v in values:
        lines.append(f"    {v!r},")
    lines.append("];\n")
    return "\n".join(lines)


def gen_scalar(name: str, value) -> str:
    return f"pub static {name}: f64 = {value!r};\n"


def main() -> int:
    out = [HEADER]
    for rust_name, py_attr, kind in TABLES:
        obj = getattr(P, py_attr)
        gen = {"vec": gen_vec, "dict": gen_dict, "scalar": gen_scalar}[kind]
        out.append(gen(rust_name, obj))
    path = sys.argv[1] if len(sys.argv) > 1 else "native/src/tables_dna.rs"
    with open(path, "w") as f:
        f.write("\n".join(out))
    total = sum(1 if k == "scalar" else len(getattr(P, a)) for _, a, k in TABLES)
    print(f"wrote {path}: {len(TABLES)} tables, {total} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
